version: '3.8'
services:
  mail-sender-service:
    image: mail-sender:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT= 8082
      - SPRING_MAIL_SENDER=${MAIL_SENDER_EMAIL}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    networks:
      - kafka-network
networks:
  kafka-network:
    external: true
